// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/widget/widget_test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/models/models.dart' as _i2;
import 'package:frontend/services/anteprojects_service.dart' as _i6;
import 'package:frontend/services/auth_service.dart' as _i3;
import 'package:frontend/services/tasks_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supabase_flutter/supabase_flutter.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnteproject_0 extends _i1.SmartFake implements _i2.Anteproject {
  _FakeAnteproject_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_1 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_2 extends _i1.SmartFake implements _i2.Comment {
  _FakeComment_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AuthState> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.AuthState>.empty(),
          )
          as _i4.Stream<_i5.AuthState>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> get isAdmin =>
      (super.noSuchMethod(
            Invocation.getter(#isAdmin),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isTutor =>
      (super.noSuchMethod(
            Invocation.getter(#isTutor),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isStudent =>
      (super.noSuchMethod(
            Invocation.getter(#isStudent),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.User?> getCurrentUserFromSupabase() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserFromSupabase, []),
            returnValue: _i4.Future<_i2.User?>.value(),
          )
          as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.User?> getCurrentUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserProfile, []),
            returnValue: _i4.Future<_i2.User?>.value(),
          )
          as _i4.Future<_i2.User?>);

  @override
  _i2.User? createUserFromLoginResponse(Map<String, dynamic>? loginResponse) =>
      (super.noSuchMethod(
            Invocation.method(#createUserFromLoginResponse, [loginResponse]),
          )
          as _i2.User?);

  @override
  _i4.Future<void> updateProfile({
    required String? fullName,
    String? phone,
    String? biography,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #phone: phone,
              #biography: biography,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasRole(_i2.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#hasRole, [role]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> saveUserSession(_i2.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserSession, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.User?> getSavedUserSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedUserSession, []),
            returnValue: _i4.Future<_i2.User?>.value(),
          )
          as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> clearSavedSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSavedSession, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> resetPasswordForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordForEmail, [email]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AnteprojectsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnteprojectsService extends _i1.Mock
    implements _i6.AnteprojectsService {
  MockAnteprojectsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Anteproject>> getAnteprojects() =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojects, []),
            returnValue: _i4.Future<List<_i2.Anteproject>>.value(
              <_i2.Anteproject>[],
            ),
          )
          as _i4.Future<List<_i2.Anteproject>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAnteprojectsWithStudentInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojectsWithStudentInfo, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Anteproject?> getAnteproject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteproject, [id]),
            returnValue: _i4.Future<_i2.Anteproject?>.value(),
          )
          as _i4.Future<_i2.Anteproject?>);

  @override
  _i4.Future<_i2.Anteproject> createAnteproject(_i2.Anteproject? anteproject) =>
      (super.noSuchMethod(
            Invocation.method(#createAnteproject, [anteproject]),
            returnValue: _i4.Future<_i2.Anteproject>.value(
              _FakeAnteproject_0(
                this,
                Invocation.method(#createAnteproject, [anteproject]),
              ),
            ),
          )
          as _i4.Future<_i2.Anteproject>);

  @override
  _i4.Future<_i2.Anteproject> updateAnteproject(
    int? id,
    _i2.Anteproject? anteproject,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAnteproject, [id, anteproject]),
            returnValue: _i4.Future<_i2.Anteproject>.value(
              _FakeAnteproject_0(
                this,
                Invocation.method(#updateAnteproject, [id, anteproject]),
              ),
            ),
          )
          as _i4.Future<_i2.Anteproject>);

  @override
  _i4.Future<void> submitAnteproject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnteproject, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> submitAnteprojectForApproval(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnteprojectForApproval, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> approveAnteproject(
    int? id,
    String? comments, {
    Map<String, dynamic>? timeline,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #approveAnteproject,
              [id, comments],
              {#timeline: timeline},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectAnteproject(int? id, String? comments) =>
      (super.noSuchMethod(
            Invocation.method(#rejectAnteproject, [id, comments]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Anteproject>> getAnteprojectsByStatus(
    _i2.AnteprojectStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojectsByStatus, [status]),
            returnValue: _i4.Future<List<_i2.Anteproject>>.value(
              <_i2.Anteproject>[],
            ),
          )
          as _i4.Future<List<_i2.Anteproject>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTutorAnteprojects() =>
      (super.noSuchMethod(
            Invocation.method(#getTutorAnteprojects, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i2.Anteproject>> getStudentAnteprojects() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentAnteprojects, []),
            returnValue: _i4.Future<List<_i2.Anteproject>>.value(
              <_i2.Anteproject>[],
            ),
          )
          as _i4.Future<List<_i2.Anteproject>>);

  @override
  _i4.Future<_i2.User?> getAnteprojectStudent(int? anteprojectId) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojectStudent, [anteprojectId]),
            returnValue: _i4.Future<_i2.User?>.value(),
          )
          as _i4.Future<_i2.User?>);

  @override
  _i4.Future<void> deleteAnteproject(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAnteproject, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.User>> getAnteprojectStudents(int? anteprojectId) =>
      (super.noSuchMethod(
            Invocation.method(#getAnteprojectStudents, [anteprojectId]),
            returnValue: _i4.Future<List<_i2.User>>.value(<_i2.User>[]),
          )
          as _i4.Future<List<_i2.User>>);
}

/// A class which mocks [TasksService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksService extends _i1.Mock implements _i7.TasksService {
  MockTasksService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Task>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getStudentTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentTasks, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByProject, [projectId]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getProjectTasksForUser(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectTasksForUser, [projectId]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<_i2.Task?> getTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i4.Future<_i2.Task?>.value(),
          )
          as _i4.Future<_i2.Task?>);

  @override
  _i4.Future<_i2.Task> createTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_1(this, Invocation.method(#createTask, [task])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> updateTask(int? id, _i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [id, task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_1(this, Invocation.method(#updateTask, [id, task])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> updateTaskStatus(int? id, _i2.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [id, status]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_1(
                this,
                Invocation.method(#updateTaskStatus, [id, status]),
              ),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> assignUserToTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#assignUserToTask, [taskId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unassignUserFromTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unassignUserFromTask, [taskId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Comment> addComment(
    int? taskId,
    String? content, {
    bool? isInternal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [taskId, content],
              {#isInternal: isInternal},
            ),
            returnValue: _i4.Future<_i2.Comment>.value(
              _FakeComment_2(
                this,
                Invocation.method(
                  #addComment,
                  [taskId, content],
                  {#isInternal: isInternal},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Comment>);

  @override
  _i4.Future<List<_i2.Comment>> getTaskComments(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskComments, [taskId]),
            returnValue: _i4.Future<List<_i2.Comment>>.value(<_i2.Comment>[]),
          )
          as _i4.Future<List<_i2.Comment>>);

  @override
  _i4.Future<void> updateKanbanPosition(
    int? taskId,
    double? newPosition, {
    required int? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateKanbanPosition,
              [taskId, newPosition],
              {#projectId: projectId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Task> moveTask({
    required int? taskId,
    required _i2.TaskStatus? fromStatus,
    required _i2.TaskStatus? toStatus,
    required int? targetIndex,
    required int? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveTask, [], {
              #taskId: taskId,
              #fromStatus: fromStatus,
              #toStatus: toStatus,
              #targetIndex: targetIndex,
              #projectId: projectId,
            }),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_1(
                this,
                Invocation.method(#moveTask, [], {
                  #taskId: taskId,
                  #fromStatus: fromStatus,
                  #toStatus: toStatus,
                  #targetIndex: targetIndex,
                  #projectId: projectId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> recalculateKanbanPositions({required int? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#recalculateKanbanPositions, [], {
              #projectId: projectId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByStatus(_i2.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [status]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByComplexity(
    _i2.TaskComplexity? complexity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByComplexity, [complexity]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksWithUpcomingDeadline({
    int? daysAhead = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksWithUpcomingDeadline, [], {
              #daysAhead: daysAhead,
            }),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<void> deleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializeKanbanPositions({required int? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#initializeKanbanPositions, [], {
              #projectId: projectId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
