// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/unit/tasks_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/models/models.dart' as _i2;
import 'package:frontend/services/tasks_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_1 extends _i1.SmartFake implements _i2.Comment {
  _FakeComment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TasksService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksService extends _i1.Mock implements _i3.TasksService {
  MockTasksService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Task>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getStudentTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getStudentTasks, []),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByProject, [projectId]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getProjectTasksForUser(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectTasksForUser, [projectId]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<_i2.Task?> getTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTask, [id]),
            returnValue: _i4.Future<_i2.Task?>.value(),
          )
          as _i4.Future<_i2.Task?>);

  @override
  _i4.Future<_i2.Task> createTask(_i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#createTask, [task])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> updateTask(int? id, _i2.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [id, task]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(this, Invocation.method(#updateTask, [id, task])),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<_i2.Task> updateTaskStatus(int? id, _i2.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [id, status]),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(#updateTaskStatus, [id, status]),
              ),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> assignUserToTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#assignUserToTask, [taskId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unassignUserFromTask(int? taskId, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unassignUserFromTask, [taskId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Comment> addComment(
    int? taskId,
    String? content, {
    bool? isInternal = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [taskId, content],
              {#isInternal: isInternal},
            ),
            returnValue: _i4.Future<_i2.Comment>.value(
              _FakeComment_1(
                this,
                Invocation.method(
                  #addComment,
                  [taskId, content],
                  {#isInternal: isInternal},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Comment>);

  @override
  _i4.Future<List<_i2.Comment>> getTaskComments(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskComments, [taskId]),
            returnValue: _i4.Future<List<_i2.Comment>>.value(<_i2.Comment>[]),
          )
          as _i4.Future<List<_i2.Comment>>);

  @override
  _i4.Future<void> updateKanbanPosition(
    int? taskId,
    double? newPosition, {
    required int? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateKanbanPosition,
              [taskId, newPosition],
              {#projectId: projectId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Task> moveTask({
    required int? taskId,
    required _i2.TaskStatus? fromStatus,
    required _i2.TaskStatus? toStatus,
    required int? targetIndex,
    required int? projectId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveTask, [], {
              #taskId: taskId,
              #fromStatus: fromStatus,
              #toStatus: toStatus,
              #targetIndex: targetIndex,
              #projectId: projectId,
            }),
            returnValue: _i4.Future<_i2.Task>.value(
              _FakeTask_0(
                this,
                Invocation.method(#moveTask, [], {
                  #taskId: taskId,
                  #fromStatus: fromStatus,
                  #toStatus: toStatus,
                  #targetIndex: targetIndex,
                  #projectId: projectId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> recalculateKanbanPositions({required int? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#recalculateKanbanPositions, [], {
              #projectId: projectId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByStatus(_i2.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByStatus, [status]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksByComplexity(
    _i2.TaskComplexity? complexity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksByComplexity, [complexity]),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<List<_i2.Task>> getTasksWithUpcomingDeadline({
    int? daysAhead = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksWithUpcomingDeadline, [], {
              #daysAhead: daysAhead,
            }),
            returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
          )
          as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<void> deleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initializeKanbanPositions({required int? projectId}) =>
      (super.noSuchMethod(
            Invocation.method(#initializeKanbanPositions, [], {
              #projectId: projectId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
