import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/models/models.dart';
import 'package:frontend/config/app_config.dart';

void main() {
  group('Backend Connection Integration Tests', () {
    testWidgets('Task model structure is correct', (WidgetTester tester) async {
      // Verificar que el modelo Task tiene la estructura correcta
      final now = DateTime.now();
      final task = Task(
        id: 1,
        projectId: 1,
        title: 'Test Task',
        description: 'Test Description',
        status: TaskStatus.pending,
        complexity: TaskComplexity.simple,
        kanbanPosition: 0,
        isAutoGenerated: false,
        createdAt: now,
        updatedAt: now,
      );

      expect(task.id, equals(1));
      expect(task.projectId, equals(1));
      expect(task.title, equals('Test Task'));
      expect(task.description, equals('Test Description'));
      expect(task.status, equals(TaskStatus.pending));
      expect(task.complexity, equals(TaskComplexity.simple));
      expect(task.kanbanPosition, equals(0));
      expect(task.isAutoGenerated, equals(false));
      expect(task.createdAt, equals(now));
      expect(task.updatedAt, equals(now));
    });

    testWidgets('Task enums have correct values', (WidgetTester tester) async {
      // Verificar que los enums tienen los valores correctos
      expect(TaskStatus.values, contains(TaskStatus.pending));
      expect(TaskStatus.values, contains(TaskStatus.inProgress));
      expect(TaskStatus.values, contains(TaskStatus.completed));

      expect(TaskComplexity.values, contains(TaskComplexity.simple));
      expect(TaskComplexity.values, contains(TaskComplexity.medium));
      expect(TaskComplexity.values, contains(TaskComplexity.complex));
    });

    testWidgets('AppConfig provides correct values', (WidgetTester tester) async {
      // Verificar que AppConfig proporciona valores correctos
      expect(AppConfig.supabaseUrl, isNotEmpty);
      expect(AppConfig.supabaseAnonKey, isNotEmpty);
      expect(AppConfig.storageUrl, isNotEmpty);
      expect(AppConfig.platformName, isNotEmpty);
      expect(AppConfig.appName, isNotEmpty);
      expect(AppConfig.appVersion, isNotEmpty);
      expect(AppConfig.environment, isNotEmpty);
      expect(AppConfig.supabaseStudioUrl, isNotEmpty);
      expect(AppConfig.inbucketUrl, isNotEmpty);
    });

    testWidgets('Task model copyWith works correctly', (WidgetTester tester) async {
      // Verificar que el método copyWith funciona correctamente
      final now = DateTime.now();
      final originalTask = Task(
        id: 1,
        projectId: 1,
        title: 'Original Task',
        description: 'Original Description',
        status: TaskStatus.pending,
        complexity: TaskComplexity.simple,
        kanbanPosition: 0,
        isAutoGenerated: false,
        createdAt: now,
        updatedAt: now,
      );

      final updatedTask = originalTask.copyWith(
        title: 'Updated Task',
        status: TaskStatus.inProgress,
      );

      expect(updatedTask.id, equals(originalTask.id));
      expect(updatedTask.projectId, equals(originalTask.projectId));
      expect(updatedTask.title, equals('Updated Task'));
      expect(updatedTask.description, equals(originalTask.description));
      expect(updatedTask.status, equals(TaskStatus.inProgress));
      expect(updatedTask.complexity, equals(originalTask.complexity));
      expect(updatedTask.kanbanPosition, equals(originalTask.kanbanPosition));
      expect(updatedTask.isAutoGenerated, equals(originalTask.isAutoGenerated));
      expect(updatedTask.createdAt, equals(originalTask.createdAt));
      expect(updatedTask.updatedAt, equals(originalTask.updatedAt));
    });

    testWidgets('Backend configuration is ready', (WidgetTester tester) async {
      // Verificar que la configuración del backend está lista
      await tester.pumpWidget(
        const MaterialApp(
          home: Scaffold(
            body: Center(
              child: Text('Backend Config Test'),
            ),
          ),
        ),
      );

      // Verificar que la configuración está disponible
      expect(AppConfig.supabaseUrl, isNotEmpty);
      expect(AppConfig.supabaseAnonKey, isNotEmpty);
      expect(AppConfig.isDevelopment, isTrue);
      expect(AppConfig.debugMode, isTrue);
    });
  });
}