import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:frontend/models/models.dart';
import 'package:frontend/screens/forms/task_form.dart';
import 'package:frontend/screens/lists/tasks_list.dart';
import 'package:frontend/screens/kanban/kanban_board.dart';

void main() {
  group('Task Navigation Flow Integration Tests', () {

    testWidgets('Task models can be instantiated correctly', (WidgetTester tester) async {
      // Este test verifica que los modelos de tarea se pueden instanciar
      // sin errores de compilación
      
      // Verificar que se pueden crear instancias de Task
      expect(() {
        final now = DateTime.now();
        return Task(
          id: 1,
          projectId: 1,
          title: 'Test Task',
          description: 'Test Description',
          status: TaskStatus.pending,
          complexity: TaskComplexity.simple,
          kanbanPosition: 0,
          isAutoGenerated: false,
          createdAt: now,
          updatedAt: now,
        );
      }, returnsNormally);
    });

    testWidgets('Task enums have correct values', (WidgetTester tester) async {
      // Verificar que los enums de tarea tienen los valores correctos
      expect(TaskStatus.values.length, equals(3));
      expect(TaskStatus.pending, isA<TaskStatus>());
      expect(TaskStatus.inProgress, isA<TaskStatus>());
      expect(TaskStatus.completed, isA<TaskStatus>());

      expect(TaskComplexity.values.length, equals(3));
      expect(TaskComplexity.simple, isA<TaskComplexity>());
      expect(TaskComplexity.medium, isA<TaskComplexity>());
      expect(TaskComplexity.complex, isA<TaskComplexity>());
    });

    testWidgets('Task form widgets can be instantiated', (WidgetTester tester) async {
      // Verificar que los widgets de formulario se pueden instanciar
      expect(() => TaskForm(projectId: 1, onSave: (_) {}), returnsNormally);
      expect(() => const TasksList(projectId: 1), returnsNormally);
      expect(() => const KanbanBoard(projectId: 1), returnsNormally);
    });

    testWidgets('Task navigation structure is correct', (WidgetTester tester) async {
      // Verificar que la estructura de navegación es correcta
      await tester.pumpWidget(
        const MaterialApp(
          home: Scaffold(
            body: Center(
              child: Text('Test Navigation'),
            ),
          ),
        ),
      );

      expect(find.text('Test Navigation'), findsOneWidget);
    });
  });
}
